#!/usr/bin/env php
<?php

require_once __DIR__.'/../vendor/autoload.php';

use MagdKudama\Scraper\Command\ScrapCommand;
use Symfony\Component\Console\Application;

$application = new Application('Web Scraper', '1.0.0');
$application->add(new ScrapCommand());

$application->run();
